"""add simulated user accounts

Revision ID: 79f1f190bb3a
Revises: b92d2f7b66b1
Create Date: 2026-09-15 11:21:28.647829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f1f190bb3a'
down_revision: Union[str, Sequence[str], None] = 'b92d2f7b66b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('mfa_enrolled', sa.Boolean(), nullable=False),
    sa.Column('password_reset_required', sa.Boolean(), nullable=False),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('last_password_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_customer_id'), 'user_accounts', ['customer_id'], unique=True)
    op.create_index(op.f('ix_user_accounts_username'), 'user_accounts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_username'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_customer_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
