"""add simulated device state

Revision ID: 81673a067f36
Revises: 79f1f190bb3a
Create Date: 2026-09-17 19:12:54.696134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81673a067f36'
down_revision: Union[str, Sequence[str], None] = '79f1f190bb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('network_adapter_enabled', sa.Boolean(), nullable=False),
    sa.Column('gateway_reachable', sa.Boolean(), nullable=False),
    sa.Column('dns_resolving', sa.Boolean(), nullable=False),
    sa.Column('internet_reachable', sa.Boolean(), nullable=False),
    sa.Column('disk_total_gb', sa.Integer(), nullable=False),
    sa.Column('disk_free_gb', sa.Integer(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Integer(), nullable=False),
    sa.Column('memory_usage_percent', sa.Integer(), nullable=False),
    sa.Column('pending_reboot', sa.Boolean(), nullable=False),
    sa.Column('primary_service_name', sa.String(length=100), nullable=True),
    sa.Column('primary_service_running', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cpu_usage_percent BETWEEN 0 AND 100', name='ck_device_states_cpu_usage'),
    sa.CheckConstraint('disk_free_gb <= disk_total_gb', name='ck_device_states_disk_capacity'),
    sa.CheckConstraint('disk_free_gb >= 0', name='ck_device_states_disk_free'),
    sa.CheckConstraint('disk_total_gb > 0', name='ck_device_states_disk_total'),
    sa.CheckConstraint('memory_usage_percent BETWEEN 0 AND 100', name='ck_device_states_memory_usage'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_states_device_id'), 'device_states', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_states_device_id'), table_name='device_states')
    op.drop_table('device_states')
    # ### end Alembic commands ###
